/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 19
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  anon_sym_RBRACK = 2,
  anon_sym_Chat_COLON = 3,
  anon_sym_From_COLON = 4,
  anon_sym_COLON = 5,
  sym_timestamp = 6,
  sym__blank = 7,
  sym__chat_text = 8,
  sym__sender_text = 9,
  sym__body_text = 10,
  sym_conversation = 11,
  sym_message = 12,
  sym_chat = 13,
  sym_sender = 14,
  sym_body = 15,
  aux_sym_conversation_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_Chat_COLON] = " Chat: ",
  [anon_sym_From_COLON] = " From: ",
  [anon_sym_COLON] = ":",
  [sym_timestamp] = "timestamp",
  [sym__blank] = "_blank",
  [sym__chat_text] = "_chat_text",
  [sym__sender_text] = "_sender_text",
  [sym__body_text] = "_body_text",
  [sym_conversation] = "conversation",
  [sym_message] = "message",
  [sym_chat] = "chat",
  [sym_sender] = "sender",
  [sym_body] = "body",
  [aux_sym_conversation_repeat1] = "conversation_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_Chat_COLON] = anon_sym_Chat_COLON,
  [anon_sym_From_COLON] = anon_sym_From_COLON,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_timestamp] = sym_timestamp,
  [sym__blank] = sym__blank,
  [sym__chat_text] = sym__chat_text,
  [sym__sender_text] = sym__sender_text,
  [sym__body_text] = sym__body_text,
  [sym_conversation] = sym_conversation,
  [sym_message] = sym_message,
  [sym_chat] = sym_chat,
  [sym_sender] = sym_sender,
  [sym_body] = sym_body,
  [aux_sym_conversation_repeat1] = aux_sym_conversation_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Chat_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_From_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_timestamp] = {
    .visible = true,
    .named = true,
  },
  [sym__blank] = {
    .visible = false,
    .named = true,
  },
  [sym__chat_text] = {
    .visible = false,
    .named = true,
  },
  [sym__sender_text] = {
    .visible = false,
    .named = true,
  },
  [sym__body_text] = {
    .visible = false,
    .named = true,
  },
  [sym_conversation] = {
    .visible = true,
    .named = true,
  },
  [sym_message] = {
    .visible = true,
    .named = true,
  },
  [sym_chat] = {
    .visible = true,
    .named = true,
  },
  [sym_sender] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_conversation_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_chat = 2,
  field_sender = 3,
  field_time = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_chat] = "chat",
  [field_sender] = "sender",
  [field_time] = "time",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_chat, 4},
    {field_sender, 6},
    {field_time, 1},
  [3] =
    {field_body, 8},
    {field_chat, 4},
    {field_sender, 6},
    {field_time, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == ':') ADVANCE(36);
      if (lookahead == '[') ADVANCE(32);
      if (lookahead == ']') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == 'C') ADVANCE(13);
      if (lookahead == 'F') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(35);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(22);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(3);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(4);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(30);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(9);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_Chat_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_From_COLON);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_timestamp);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__blank);
      if (lookahead == '\n') ADVANCE(38);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0, .external_lex_state = 3},
  [8] = {.lex_state = 0, .external_lex_state = 4},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_Chat_COLON] = ACTIONS(1),
    [anon_sym_From_COLON] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_timestamp] = ACTIONS(1),
    [sym__blank] = ACTIONS(1),
    [sym__chat_text] = ACTIONS(1),
    [sym__sender_text] = ACTIONS(1),
    [sym__body_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_conversation] = STATE(12),
    [sym_message] = STATE(3),
    [aux_sym_conversation_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(9), 1,
      sym__blank,
    ACTIONS(11), 1,
      sym__body_text,
    STATE(6), 1,
      sym_body,
    ACTIONS(7), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [14] = 3,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(4), 2,
      sym_message,
      aux_sym_conversation_repeat1,
  [25] = 3,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    STATE(4), 2,
      sym_message,
      aux_sym_conversation_repeat1,
  [36] = 1,
    ACTIONS(20), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym__blank,
  [42] = 2,
    ACTIONS(24), 1,
      sym__blank,
    ACTIONS(22), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [50] = 2,
    ACTIONS(26), 1,
      sym__chat_text,
    STATE(16), 1,
      sym_chat,
  [57] = 2,
    ACTIONS(28), 1,
      sym__sender_text,
    STATE(18), 1,
      sym_sender,
  [64] = 1,
    ACTIONS(30), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [69] = 1,
    ACTIONS(32), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [74] = 1,
    ACTIONS(34), 1,
      sym_timestamp,
  [78] = 1,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
  [82] = 1,
    ACTIONS(38), 1,
      anon_sym_RBRACK,
  [86] = 1,
    ACTIONS(40), 1,
      anon_sym_Chat_COLON,
  [90] = 1,
    ACTIONS(42), 1,
      anon_sym_From_COLON,
  [94] = 1,
    ACTIONS(44), 1,
      anon_sym_From_COLON,
  [98] = 1,
    ACTIONS(46), 1,
      anon_sym_COLON,
  [102] = 1,
    ACTIONS(48), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 14,
  [SMALL_STATE(4)] = 25,
  [SMALL_STATE(5)] = 36,
  [SMALL_STATE(6)] = 42,
  [SMALL_STATE(7)] = 50,
  [SMALL_STATE(8)] = 57,
  [SMALL_STATE(9)] = 64,
  [SMALL_STATE(10)] = 69,
  [SMALL_STATE(11)] = 74,
  [SMALL_STATE(12)] = 78,
  [SMALL_STATE(13)] = 82,
  [SMALL_STATE(14)] = 86,
  [SMALL_STATE(15)] = 90,
  [SMALL_STATE(16)] = 94,
  [SMALL_STATE(17)] = 98,
  [SMALL_STATE(18)] = 102,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conversation, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 8, 0, 1),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conversation, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_conversation_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_conversation_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 9, 0, 2),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 9, 0, 1),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 10, 0, 2),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [36] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chat, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sender, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__chat_text = 0,
  ts_external_token__sender_text = 1,
  ts_external_token__body_text = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__chat_text] = sym__chat_text,
  [ts_external_token__sender_text] = sym__sender_text,
  [ts_external_token__body_text] = sym__body_text,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__chat_text] = true,
    [ts_external_token__sender_text] = true,
    [ts_external_token__body_text] = true,
  },
  [2] = {
    [ts_external_token__body_text] = true,
  },
  [3] = {
    [ts_external_token__chat_text] = true,
  },
  [4] = {
    [ts_external_token__sender_text] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_whatsapp_external_scanner_create(void);
void tree_sitter_whatsapp_external_scanner_destroy(void *);
bool tree_sitter_whatsapp_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_whatsapp_external_scanner_serialize(void *, char *);
void tree_sitter_whatsapp_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_whatsapp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_whatsapp_external_scanner_create,
      tree_sitter_whatsapp_external_scanner_destroy,
      tree_sitter_whatsapp_external_scanner_scan,
      tree_sitter_whatsapp_external_scanner_serialize,
      tree_sitter_whatsapp_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
